using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace Dreamine.MVVM.Generators
{
    /// <summary>
    /// [DreamineEntry]가 부여된 App 클래스에 대해
    /// WPF 부트스트랩 코드를 생성합니다.
    /// </summary>
    [Generator]
    public sealed class DreamineEntryGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Generator 초기화를 수행합니다.
        /// </summary>
        /// <param name="context">Generator 초기화 컨텍스트입니다.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            IncrementalValueProvider<INamedTypeSymbol?> entryAttrSymbol = context.CompilationProvider
                .Select(static (compilation, _) =>
                    compilation.GetTypeByMetadataName("Dreamine.MVVM.Attributes.DreamineEntryAttribute"));

            IncrementalValueProvider<ImmutableArray<(INamedTypeSymbol Symbol, string Namespace)>> candidates = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is ClassDeclarationSyntax classDeclaration && classDeclaration.AttributeLists.Count > 0,
                    static (syntaxContext, _) => syntaxContext)
                .Combine(entryAttrSymbol)
                .Select(static (pair, _) =>
                {
                    GeneratorSyntaxContext syntaxContext = pair.Left;
                    INamedTypeSymbol? attributeSymbol = pair.Right;

                    return GetEntryCandidate(syntaxContext, attributeSymbol);
                })
                .Where(static candidate => candidate is not null)
                .Select(static (candidate, _) => candidate!.Value)
                .Collect();

            context.RegisterSourceOutput(candidates, static (sourceProductionContext, entryCandidates) =>
            {
                foreach ((INamedTypeSymbol classSymbol, string @namespace) in entryCandidates)
                {
                    string className = classSymbol.Name;
                    string source = GenerateEntrySource(@namespace, className);

                    sourceProductionContext.AddSource(
                        $"{className}_DreamineApp.g.cs",
                        SourceText.From(source, Encoding.UTF8));
                }
            });
        }

        /// <summary>
        /// [DreamineEntry] 속성이 적용된 클래스를 찾습니다.
        /// </summary>
        /// <param name="ctx">구문 컨텍스트입니다.</param>
        /// <param name="entryAttrSymbol">DreamineEntryAttribute 심볼입니다.</param>
        /// <returns>대상 클래스와 네임스페이스입니다.</returns>
        private static (INamedTypeSymbol Symbol, string Namespace)? GetEntryCandidate(
            GeneratorSyntaxContext ctx,
            INamedTypeSymbol? entryAttrSymbol)
        {
            if (ctx.Node is not ClassDeclarationSyntax classDeclaration)
            {
                return null;
            }

            if (ctx.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            {
                return null;
            }

            if (classSymbol.GetAttributes()
                .Any(attribute => SymbolEqualityComparer.Default.Equals(attribute.AttributeClass, entryAttrSymbol)))
            {
                string @namespace = classSymbol.ContainingNamespace.ToDisplayString();
                return (classSymbol, @namespace);
            }

            return null;
        }

        /// <summary>
        /// Dreamine Entry용 App partial class 소스 코드를 생성합니다.
        /// </summary>
        /// <param name="namespaceName">대상 네임스페이스입니다.</param>
        /// <param name="className">대상 클래스 이름입니다.</param>
        /// <returns>생성된 소스 코드 문자열입니다.</returns>
        private static string GenerateEntrySource(string namespaceName, string className)
        {
            return $$"""
// <auto-generated />
using System.Windows;
using System.Windows.Controls;
using Dreamine.MVVM.Core;
using Dreamine.MVVM.Locators;
using Dreamine.MVVM.Interfaces.Navigation;
using Dreamine.MVVM.Locators.Wpf;

namespace {{namespaceName}}
{
    public partial class {{className}} : Application
    {
        /// <summary>
        /// 애플리케이션 시작 시 초기화를 수행합니다.
        /// </summary>
        /// <param name="e">시작 인자입니다.</param>
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);

            var rootAssembly = typeof(App).Assembly;

            RegisterBefore();

            DMContainer.AutoRegisterAll(rootAssembly);
            ViewModelLocator.RegisterAll(rootAssembly);

            EventManager.RegisterClassHandler(
                typeof(FrameworkElement),
                FrameworkElement.LoadedEvent,
                new RoutedEventHandler(AttachViewModelIfExists));

            ShowMainWindow();
            Dispatcher.InvokeAsync(RegisterAfter);
        }

        static partial void RegisterBefore();
        static partial void RegisterAfter();
        static partial void ShowMainWindow();

        /// <summary>
        /// View에 대응되는 ViewModel이 존재하면 자동으로 DataContext를 연결합니다.
        /// </summary>
        /// <param name="sender">이벤트 송신자입니다.</param>
        /// <param name="e">라우팅 이벤트 인자입니다.</param>
        private static void AttachViewModelIfExists(object sender, RoutedEventArgs e)
        {
            if (sender is not FrameworkElement view)
            {
                return;
            }

            if (view.DataContext != null)
            {
                return;
            }

            if (view is not Window && view is not UserControl && view is not Page)
            {
                return;
            }

            var vm = ViewModelLocator.Resolve(view.GetType());
            if (vm != null)
            {
                view.DataContext = vm;
            }
        }
    }
}
""";
        }
    }
}