using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System;
using System.Linq;
using System.Text;

namespace Dreamine.MVVM.Generators
{
    /// <summary>
    /// [DreamineEntry]가 부여된 App 클래스에 대해
    /// WPF 부트스트랩 코드를 생성합니다.
    /// </summary>
    [Generator]
    public sealed class DreamineEntryGenerator : IIncrementalGenerator
    {
        /// <summary>
        /// Generator 초기화를 수행합니다.
        /// </summary>
        /// <param name="context">Generator 초기화 컨텍스트입니다.</param>
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var entryAttrSymbol = context.CompilationProvider
                .Select(static (c, _) =>
                    c.GetTypeByMetadataName("Dreamine.MVVM.Attributes.DreamineEntryAttribute"));

            var candidates = context.SyntaxProvider
                .CreateSyntaxProvider(
                    static (node, _) => node is ClassDeclarationSyntax cds && cds.AttributeLists.Count > 0,
                    static (ctx, _) => ctx)
                .Combine(entryAttrSymbol)
                .Select(static (pair, _) =>
                {
                    var syntaxContext = pair.Left;
                    var attributeSymbol = pair.Right;
                    return GetEntryCandidate(syntaxContext, attributeSymbol);
                })
                .Where(static x => x is not null)
                .Select(static (x, _) => x!.Value)
                .Collect();

            context.RegisterSourceOutput(candidates, static (spc, list) =>
            {
                foreach (var (classSymbol, ns) in list)
                {
                    var className = classSymbol.Name;

                    var sb = new StringBuilder();
                    sb.AppendLine("// <auto-generated />");
                    sb.AppendLine("using System.Windows;");
                    sb.AppendLine("using System.Windows.Controls;");
                    sb.AppendLine("using Dreamine.MVVM.Core;");
                    sb.AppendLine("using Dreamine.MVVM.Locators;");
                    sb.AppendLine("using Dreamine.MVVM.Interfaces.Navigation;");
                    sb.AppendLine("using Dreamine.MVVM.Locators.Wpf;");
                    sb.AppendLine();
                    sb.AppendLine($"namespace {ns}");
                    sb.AppendLine("{");
                    sb.AppendLine($"    public partial class {className} : Application");
                    sb.AppendLine("    {");
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine("        /// 애플리케이션 시작 시 초기화를 수행합니다.");
                    sb.AppendLine("        /// </summary>");
                    sb.AppendLine("        /// <param name=\"e\">시작 인자입니다.</param>");
                    sb.AppendLine("        protected override void OnStartup(StartupEventArgs e)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            base.OnStartup(e);");
                    sb.AppendLine();
                    sb.AppendLine("            var rootAssembly = typeof(App).Assembly;");
                    sb.AppendLine();
                    sb.AppendLine("            RegisterBefore();");
                    sb.AppendLine();
                    sb.AppendLine("            DMContainer.AutoRegisterAll(rootAssembly);");
                    sb.AppendLine("            ViewModelLocator.RegisterAll(rootAssembly);");
                    sb.AppendLine();
                    sb.AppendLine("            EventManager.RegisterClassHandler(");
                    sb.AppendLine("                typeof(FrameworkElement),");
                    sb.AppendLine("                FrameworkElement.LoadedEvent,");
                    sb.AppendLine("                new RoutedEventHandler(AttachViewModelIfExists));");
                    sb.AppendLine();
                    sb.AppendLine("            ShowMainWindow();");
                    sb.AppendLine("            Dispatcher.InvokeAsync(RegisterAfter);");
                    sb.AppendLine("        }");
                    sb.AppendLine();
                    sb.AppendLine("        static partial void RegisterBefore();");
                    sb.AppendLine("        static partial void RegisterAfter();");
                    sb.AppendLine("        static partial void ShowMainWindow();");
                    sb.AppendLine();
                    sb.AppendLine("        /// <summary>");
                    sb.AppendLine("        /// View에 대응되는 ViewModel이 존재하면 자동으로 DataContext를 연결합니다.");
                    sb.AppendLine("        /// </summary>");
                    sb.AppendLine("        /// <param name=\"sender\">이벤트 송신자입니다.</param>");
                    sb.AppendLine("        /// <param name=\"e\">라우팅 이벤트 인자입니다.</param>");
                    sb.AppendLine("        private static void AttachViewModelIfExists(object sender, RoutedEventArgs e)");
                    sb.AppendLine("        {");
                    sb.AppendLine("            if (sender is not FrameworkElement view)");
                    sb.AppendLine("                return;");
                    sb.AppendLine();
                    sb.AppendLine("            if (view.DataContext != null)");
                    sb.AppendLine("                return;");
                    sb.AppendLine();
                    sb.AppendLine("            if (view is not Window && view is not UserControl && view is not Page)");
                    sb.AppendLine("                return;");
                    sb.AppendLine();
                    sb.AppendLine("            var vm = ViewModelLocator.Resolve(view.GetType());");
                    sb.AppendLine("            if (vm != null)");
                    sb.AppendLine("                view.DataContext = vm;");
                    sb.AppendLine("        }");
                    sb.AppendLine("    }");
                    sb.AppendLine("}");

                    spc.AddSource($"{className}_DreamineApp.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
                }
            });
        }

        /// <summary>
        /// [DreamineEntry] 속성이 적용된 클래스를 찾습니다.
        /// </summary>
        /// <param name="ctx">구문 컨텍스트입니다.</param>
        /// <param name="entryAttrSymbol">DreamineEntryAttribute 심볼입니다.</param>
        /// <returns>대상 클래스와 네임스페이스입니다.</returns>
        private static (INamedTypeSymbol Symbol, string Namespace)? GetEntryCandidate(
            GeneratorSyntaxContext ctx,
            INamedTypeSymbol? entryAttrSymbol)
        {
            if (ctx.Node is not ClassDeclarationSyntax cds)
                return null;

            if (ctx.SemanticModel.GetDeclaredSymbol(cds) is not INamedTypeSymbol classSymbol)
                return null;

            foreach (var attr in classSymbol.GetAttributes())
            {
                if (SymbolEqualityComparer.Default.Equals(attr.AttributeClass, entryAttrSymbol))
                {
                    var ns = classSymbol.ContainingNamespace.ToDisplayString();
                    return (classSymbol, ns);
                }
            }

            return null;
        }
    }
}